[tool.ruff]

line-length = 120
target-version = "py310"
select = [
    "F", "E", "I", "C90", "UP", "YTT", "ANN", "S", "BLE", "B", "A", "COM", "C4", "DTZ",
    "EM", "ISC", "G", "INP", "PIE", "T20", "Q003", "RSE", "RET", "SIM", "TID", "PTH", 
    "ERA", "PD", "PLC", "PLE", "PLR", "PLW", "TRY", "NPY", "RUF"
]
ignore = ["G002", "TRY002", "S101", "PLR2004", "SIM105"]
unfixable = ["C90", "S101", "ERA"]
